language: scala
jdk: oraclejdk8
scala:
   - 2.10.7
   - 2.11.12
   - 2.12.8
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
sbt_args: -J-Dproject.version=travis-SNAPSHOT
before_install:
  - unset JVM_OPTS SBT_OPTS
sudo: false
